# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Polka
email: phebepolk@gmail.com
description: Polka is a developer and data scientist.
baseurl: /portfolio # the subpath of your site, e.g. /blog
url: polkapolka.github.io/polka # the base hostname & protocol for your site
twitter_username: polkphebe
github_username:  polkapolka

# Build settings
markdown: kramdown
